### ISSUE TITLE
How to load test Keycloak

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak-sre-sig#3]
### Describe the topic

- Introduction of keycloak-benchmark project
- Identifying possible enhancements
- Presenting custom community solutions

**Comment by wkloucek** [comment]
We at [ownCloud](https://github.com/owncloud) use our loadtesting suite [cdperf](https://github.com/owncloud/cdperf) based on [K6](https://k6.io/).

It is intended for loadtesting our filesharing product oCIS. Since we're using OIDC for authentication, we also needed to implement OIDC authentication flows in the K6 scripts. Which basically brings us free Keycloak loadtests since we mostly care about concurrent logins and sessions.

**Comment by mhajas** [comment]
### Meeting announcement

Hello all, we plan to have a meeting on this topic on **October 14th at 4pm - 5:30pm CET**

#### Meeting purpose
The desired outcome is to identity different approaches for load testing Keycloak with their individual strengths, and which tools to recommend to the broader Keycloak community.

#### Topics and presenters

1. Current state of Keycloak benchmark (@ahus1 and @mhajas))
2. Keycloak with many (1M+) offline sessions using Azure Load Testing (@sschu)
3. Load testing using "f1" (golang based load testing library) and our rationale behind not using Keycloak benchmark (@dominikschlosser and Stefan Klein)

**Meeting link:** https://meet.google.com/mrp-qifx-xsp

**Comment by ahus1** [comment]
The transcript and the recording is now available at https://www.keycloak.org/keycloak-sre-sig/meetings/2024/meeting-2024-10-14
